spring:
  datasource:
    url: jdbc:h2:mem:account-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  cloud:
    stream:
      rabbit:
        bindings:
          transaction-channel:
            consumer:
              exchangeType: fanout
            destination: transaction-exchange
            group: transaction-group
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    sender:
      type: web
  sleuth:
    stream:
      enabled: false
    sampler:
      probability: 1

server:
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS