spring:
  application:
    name: customer-service

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: ALWAYS