spring:
  application:
    name: gateway-service

zuul:
  routes:
    account:
      id: accounts
      path: /api/accounts/**
      serviceId: account-service
    customer:
      id: customers
      path: /api/customers/**
      serviceId: customer-service
    transaction:
      id: transactions
      path: /api/transactions/**
      serviceId: transaction-service