spring:
  application:
    name: gateway-service

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: ALWAYS

zuul:
  routes:
    account:
      id: accounts
      path: /api/accounts/**
      serviceId: account-service
    customer:
      id: customers
      path: /api/customers/**
      serviceId: customer-service
    transaction:
      id: transactions
      path: /api/transactions/**
      serviceId: transaction-service