spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/account-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  rabbitmq:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    stream:
      rabbit:
        bindings:
          transaction-channel:
            consumer:
              exchangeType: fanout
            destination: transaction-exchange
            group: transaction-group