apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: banking-api
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
      annotations:
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: gateway-service
          image: devmeetup/gateway-service:1.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: banking-api
  labels:
    app: gateway-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: gateway-service