apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: banking-api
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: gedao/account-service:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: postgres-password
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: banking-api
  labels:
    app: account-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: account-service